Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieBlend.Services;
using MovieBlend.Models;
namespace MovieBlend.Controllers
{
    public class MovieController : Controller
    {
        private readonly IPostDataService _moviedataService;
        public MovieController(IPostDataService movieDataService) {
            _moviedataService=movieDataService;
        } 
        public async Task<IActionResult> Index()
        {
            var items=await _moviedataService.GetIncompleteItemsAsync_Movie();
            var model=new MovieDataViewModel(){
                Movies=items
            };
            
            return View(model);
        }
    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieBlend.Models;
using MovieBlend.Services;
using System.IO;
using System.Drawing;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;


namespace MovieBlend.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private static Guid imageid;
        private static Models.Image ImageEntity=new Models.Image();
        static bool isMovie = false;
        private readonly IImageDataService _imageDataservice;
        private readonly IPostDataService _postdataService;
        private readonly UserManager<IdentityUser> _usermanger;
        public PostController(IImageDataService imageDataservice,IPostDataService movieDataService,UserManager<IdentityUser>userManager)
        {
            _imageDataservice=imageDataservice;
            _postdataService = movieDataService;
            _usermanger = userManager;

        }
        public IActionResult Cat_select()
        {
            return View("UploadPic");
        }
        [HttpPost]
        public async Task<IActionResult> UploadImage(IList<IFormFile> files)
        {
            IFormFile uploadedImage = files.FirstOrDefault();
            if (uploadedImage != null || uploadedImage.ContentType.ToLower().StartsWith("image/"))
            {
                MemoryStream ms = new MemoryStream();
                uploadedImage.OpenReadStream().CopyTo(ms);

                System.Drawing.Image image = System.Drawing.Image.FromStream(ms);
                ImageEntity.Id=Guid.NewGuid();
                ImageEntity.Name=uploadedImage.FileName;
                ImageEntity.Data=ms.ToArray();
                ImageEntity.Width=image.Width;
                ImageEntity.Height=image.Height;
                ImageEntity.ContentType=uploadedImage.ContentType;
                imageid=ImageEntity.Id;
                Console.WriteLine("WIAT WTAH" + imageid);
                await _imageDataservice.AddImageDataAsync(ImageEntity);
            }
            return View("post_entry");
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> AddPost(MovieData dummyData)
        {
            if (dummyData.Catagoryx == Catagory.Movie) isMovie = true;
            else isMovie = false;
            var currentUser = await _usermanger.GetUserAsync(User);
            if (currentUser == null) return Challenge();
            if (ImageEntity.Id != imageid)
            {
                Console.WriteLine("WAIT WHAT?" + imageid + " " + ImageEntity.Id);
            }
            MovieData newmovie = new MovieData()
            {
                Postedate = DateTimeOffset.Now,
                Id = Guid.NewGuid(),
                Title = dummyData.Title,
                Release = dummyData.Release,
                Genre = dummyData.Genre,
                Description = dummyData.Description,
                Language = dummyData.Language,
                PosterId = currentUser.Id,
                User_name = currentUser.UserName,
                Cover_pic_id = ImageEntity.Id,
                _Privacy = dummyData._Privacy
            };
            if (isMovie==true)
            {
                newmovie.Catagoryx = Catagory.Movie;
                if (!ModelState.IsValid)
                {
                    return RedirectToAction("Add_entry_movie");
                }
                var successful = await _postdataService.AddPostDataAsync(newmovie);
                if (!successful)
                {
                    return BadRequest("Couldnot Post Your Entry");
                }
                return RedirectToAction("Cat_select");
            }
            else
            {
                newmovie.Catagoryx = Catagory.Tv;
                if (!ModelState.IsValid)
                {
                    return RedirectToAction("Add_entry_TV");
                }
            
                var successful = await _postdataService.AddPostDataAsync(newmovie);
                if (!successful)
                {
                    return BadRequest("Couldnot Post Your Entry");
                }
                return RedirectToAction("Cat_select");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieBlend</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.3"></script>
    <div id="fb-root"></div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-fw fa-video-camera"></i>MovieBlend</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <!--<li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Movie" asp-area="" asp-action="Index"><i class="fa fa-fw fa-file-movie-o"></i>Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="TV" asp-area="" asp-action="Index"><i class="fa fa-fw fa-tv"></i>TV</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Post" asp-area="" asp-action="cat_select">Create</a>
                        </li>
                        -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div>
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - MovieBlend - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>