Controllers/EditDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using MovieBlend.Models;
using System.IO;
using System.Drawing;
using MovieBlend.Services;
using Microsoft.AspNetCore.Authorization;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MovieBlend.Controllers
{
    [Authorize]
    public class EditDataController : Controller
    {
        private IPostDataService _postDataService;
        private static MovieData maindata=new MovieData();
        public EditDataController(IPostDataService postDataService)
        {
            _postDataService = postDataService;
        }
        
        public async Task<IActionResult> Index(string data)
        {
            maindata = new MovieData();
            var datax = Newtonsoft.Json.JsonConvert.DeserializeObject<string>(data);
            var arr = await _postDataService.Getdatabyid(datax);
            maindata = arr;
            return View(arr);
        }
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(MovieData newdata)
        {
            newdata.Id = maindata.Id;
            newdata.Postedate = maindata.Postedate;
            newdata.User_name = maindata.User_name;
            newdata.PosterId = maindata.PosterId;
            newdata.Cover_pic_id = maindata.Cover_pic_id;
            await _postDataService.UpdateData(newdata);
            return RedirectToAction("Index","Home");
        }
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(MovieData newdata)
        {
       
            newdata.Id = maindata.Id;
            newdata.Postedate = maindata.Postedate;
            newdata.User_name = maindata.User_name;
            newdata.PosterId = maindata.PosterId;
            newdata.Cover_pic_id = maindata.Cover_pic_id;
            await _postDataService.DeleteData(newdata);
            return RedirectToAction("Index","Home");
        }

    }
}

Controllers/PostDetailController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieBlend.Models;
using MovieBlend.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.IO;

namespace MovieBlend.Controllers
{
    [Authorize]
   
    public class PostDetailController : Controller
    {

        
        //private readonly ICommentDataService _commentdataServices;
        private readonly IPostDataService _postDataService;
        private readonly IImageDataService _imageDataservice;
        private static MovieData maindata=new MovieData();
        private readonly UserManager<IdentityUser> _usermanger;
        public PostDetailController(IImageDataService imageDataservice,IPostDataService postData, UserManager<IdentityUser> usermanager)
        {
            _imageDataservice=imageDataservice;
           // _commentdataServices=commentdataService;
            _usermanger = usermanager;
            _postDataService = postData;
        }

        public async Task<IActionResult> Index(string data)
        {
            var datax = Newtonsoft.Json.JsonConvert.DeserializeObject<string>(data);
            var arr =await _postDataService.Getdatabyid(datax);
            maindata=arr;
            return View(arr);
        }
        [HttpGet]
        public async Task<FileStreamResult> ViewImage(Guid id)
        {

            Models.Image image = await _imageDataservice.GetDataByIdAsync(id);

            MemoryStream ms = new MemoryStream(image.Data);

            return new FileStreamResult(ms, image.ContentType);
        }
    }
}

Views/PostDetail/Index.cshtml
@model MovieData
@{
    ViewData["Title"] = Model.Title;
}
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.4/vue.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.16.2/axios.min.js"></script>
<script src="https://js.pusher.com/4.4/pusher.min.js"></script>
@using Humanizer
@using StmlParsing
@using Newtonsoft.Json
<style>
    .user_name {
        font-size: 14px;
        font-weight: bold;
    }

    .comments-list .media {
        border-bottom: 1px dotted #ccc;
    }

    h1 {
        color: snow;
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
    }

    h3 {
        text-align: center;
        color: snow;
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
    }

    .poster_name {
        text-align: left;
        color: darkred;
        text-decoration: underline
    }

    section {
        width: 100%;
        float: left;
    }

    .banner-section {
        background-image: url("https://static.pexels.com/photos/373912/pexels-photo-373912.jpeg");
        background-size: cover;
        height: 380px;
        left: 0;
        position: absolute;
        top: inherit;
        background-position: 0;
    }

    .post-title-block {
        padding: 100px 0;
    }

        .post-title-block h1 {
            color: #fff;
            font-size: 85px;
            font-weight: bold;
            text-transform: capitalize;
        }

        .post-title-block li {
            font-size: 20px;
            color: #fff;
        }

    .image-block {
        float: left;
        width: 100%;
        margin-bottom: 10px;
    }

    .footer-link {
        float: left;
        width: 100%;
        background: #222222;
        text-align: center;
        padding: 30px;
    }

        .footer-link a {
            color: #A9FD00;
            font-size: 18px;
            text-transform: uppercase;
        }

    .div-post {
        margin-top: 45px;
    }

    img {
        all: inherit;
        align-content: center;
        height: 380px;
    }
</style>
<div>
    <section class="banner-section">
        <img src="/PostDetail/ViewImage/@Model.Cover_pic_id" />
    </section>
    <section class="post-content-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 post-title-block">
                    <h1 class="text-center">@Model.Title</h1>
                    <h3> @Model.Release | @Model.Language | @Model.Genre</h3>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 div-post">
                    <p>
                        <h6 class="poster_name">Posted By @Model.User_name</h6>
                        <h7 class="poster_name">Posted @Model.Postedate.Humanize()</h7>
                        <br />@Html.Raw(@StmlParser.Parse(Model.Description))
                    </p>
                    @if (User.Identity.Name.ToString() == Model.User_name)
                    {

                        <button class="btn btn-danger" onclick="location.href='@Url.Action("Index", "EditData", new { @data = JsonConvert.SerializeObject(Model.Id) })'"><i class="fa fa-fw fa-edit"></i>Edit</button>
                    }
                </div>
            </div>
        </div>
    </section>
    <div class="fb-comments" data-href="https://localhost:5001/PostDetail/@Model.Id" data-width="" data-numposts="10"></div>
</div>