Controllers/MyPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieBlend.Services;
using MovieBlend.Models;
using Microsoft.AspNetCore.Identity;

namespace MovieBlend.Controllers
{
    public class MyPostController : Controller
    {
        private readonly IPostDataService _myPostdataService;
        private readonly UserManager<IdentityUser> _usermanger;
        public MyPostController(IPostDataService movieDataService, UserManager<IdentityUser> userManager)
        {
            _usermanger = userManager;
            _myPostdataService = movieDataService;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _usermanger.GetUserAsync(User);
            if (currentUser == null) return Challenge();
            var items = await _myPostdataService.GetIncompleteItemsAsync_MyPost(currentUser.Id);
            var model = new MovieDataViewModel()
            {
                Movies = items
            };
            return View(model);
        }
    }
}

Controllers/PostDetailController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieBlend.Models;
using MovieBlend.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.IO;

namespace MovieBlend.Controllers
{
    [Authorize]
   
    public class PostDetailController : Controller
    {

        
        //private readonly ICommentDataService _commentdataServices;
        private readonly IPostDataService _postDataService;
        private readonly IImageDataService _imageDataservice;
        private static MovieData maindata=new MovieData();
        private readonly UserManager<IdentityUser> _usermanger;
        public PostDetailController(IImageDataService imageDataservice,IPostDataService postData, UserManager<IdentityUser> usermanager)
        {
            _imageDataservice=imageDataservice;
           // _commentdataServices=commentdataService;
            _usermanger = usermanager;
            _postDataService = postData;
        }

        public async Task<IActionResult> Index(string data)
        {
            var datax = Newtonsoft.Json.JsonConvert.DeserializeObject<string>(data);
            var arr =await _postDataService.Getdatabyid(datax);
            maindata=arr;
            return View(arr);
        }
        [HttpGet]
        public async Task<FileStreamResult> ViewImage(Guid id)
        {

            Models.Image image = await _imageDataservice.GetDataByIdAsync(id);

            MemoryStream ms = new MemoryStream(image.Data);

            return new FileStreamResult(ms, image.ContentType);
        }
    }
}

Views/MyPost/Index.cshtml
@model MovieDataViewModel
@using Newtonsoft.Json
@using Humanizer
@using StmlParsing
@{
    ViewData["Title"] = "My Posts";
}
<link href="~/css/invert.css" rel="stylesheet" />
<div class="panel panel-default Movie-panel">
    <div class="panel-heading">@ViewData["Title"]</div>
    <div class="card-columns">
        @foreach (var item in Model.Movies)
        {

            <div class="card text-center">
                <div class="card-header">
                    @item.Genre | @item.Language |@item.Release
                </div>
                <div class="card-body" style="background:url('/PostDetail/ViewImage/@item.Cover_pic_id')">
                    <h5 class="card-title text-light" role="textbox" aria-multiline="true">
                        @item.Title
                    </h5>
                    <p class="card-text text-light"> @Html.Raw(@StmlParser.Parse(item.Description))</p>
                    <a class="btn btn-info" onclick="location.href='@Url.Action("Index","PostDetail",new { @data=JsonConvert.SerializeObject(item.Id)})'">Details</a>
                </div>

                <div class="card-footer text-muted">
                    Posted @item.Postedate.Humanize() By @item.User_name
                </div>
            </div>
        }
    </div>
</div>